### ISSUE TITLE
Can we update the cards.json, or have this pull from a web service instead?

### ISSUE THREAD

**Issue by mkmurray** [gabrielrios/alfred2-hearthstone#1]
I took a 30-minute stab at trying to get this to work with the latest `cards.json` from [https://api.hearthstonejson.com/v1/latest/enUS/cards.json](https://api.hearthstonejson.com/v1/latest/enUS/cards.json). It involved changing the encoding of the file from UTF-8 to ASCII, and then it looks like there are some unexpected tokens in the parsing now.

Anyone interested in getting this up-to-speed with the latest cards?

**Comment by mkmurray** [comment]
Anyone interested? @gabrielrios @zhaocai

**Comment by gabrielrios** [comment]
Hi @mkmurray, so I kind of stopped playing hearthstone that's why I haven't updated any of this, but I'll try to look at it this week

**Comment by mkmurray** [comment]
@gabrielrios Just wondering if I can help somehow. Does this appear to be an easy fix? Or would the whole model have to be updated to match the API now?

**Comment by kalebhermes** [comment]
Hey! I actually spent some time today and updated this to function with all the cards though One Night in Karazhan! It will need to have cards.json updated with each new release however. Assuming they don't change the way that they format that file, it should just work from here on out though!

**Comment by gabrielrios** [comment]
closed by #2
